import type { VoteItem } from "./types";

export const VOTE_ITEMS: Record<string, VoteItem[]> = {
  charlie: [
    {
      id: "ramen",
      emoji: "🍜",
      name: "Spicy Miso Ramen",
      tags: ["Vegan", "Spicy"],
      price: 9.5,
      votes: 12,
      tone: "#FFE2D6",
    },
    {
      id: "bowl",
      emoji: "🥘",
      name: "Korean Rice Bowl",
      tags: ["Gluten-free", "Spicy"],
      price: 10.25,
      votes: 18,
      tone: "#FFE9D6",
    },
    {
      id: "salad",
      emoji: "🥗",
      name: "Crunchy Thai Salad",
      tags: ["Vegan", "Gluten-free"],
      price: 8.75,
      votes: 7,
      tone: "#E6F1E0",
    },
    {
      id: "burrito",
      emoji: "🌯",
      name: "Breakfast Burrito",
      tags: ["Veggie", "High-protein"],
      price: 7.5,
      votes: 21,
      tone: "#FFF1D6",
    },
  ],
  mcnay: [
    {
      id: "sandwich",
      emoji: "🥪",
      name: "Pesto Caprese Sub",
      tags: ["Veggie"],
      price: 8.25,
      votes: 14,
      tone: "#E6F1E0",
    },
    {
      id: "matcha",
      emoji: "🍵",
      name: "Iced Matcha Latte",
      tags: ["Vegan-opt"],
      price: 5.5,
      votes: 22,
      tone: "#E0EFE3",
    },
    {
      id: "boba",
      emoji: "🧋",
      name: "Brown Sugar Boba",
      tags: ["Sweet"],
      price: 6.0,
      votes: 17,
      tone: "#EFE0F0",
    },
    {
      id: "wrap",
      emoji: "🌯",
      name: "Buffalo Chick Wrap",
      tags: ["High-protein", "Spicy"],
      price: 9.0,
      votes: 11,
      tone: "#FFE2D6",
    },
  ],
};
