import BriefView from "@/components/manager/BriefView";
import { PageHeader } from "@/components/manager/Card";
import { VENUE_LABEL, type Venue } from "@/lib/manager/types";

export default function BriefPage({
  params,
}: {
  params: { venue: string };
}) {
  const venue = params.venue as Venue;
  return (
    <>
      <PageHeader
        title="AI Ops Brief"
        subtitle={`${VENUE_LABEL[venue]} · auto-generated by Claude from today's student input`}
      />
      <BriefView venue={venue} />
    </>
  );
}
